var crunchings = {
  "Acorn Squash": true,
  "Agar-agar": false,
  "Agave syrup": false,
  "Algae": false,
  "Allspice": true,
  "Almond butter": true,
  "Almond milk": true,
  "Almond oil": true,
  "Almonds": true,
  "Aloe Vera": false,
  "Amaranth flour": false,
  "Anchovies": true,
  "Apple Cider": true,
  "Apple Juice": false,
  "Apples": true,
  "Apricots": true,
  "Arrowroot": false,
  "Artichokes (French)": true,
  "Artichokes (Jerusalem)": false,
  "Ascorbic acid": true,
  "Asiago cheese": true,
  "Asparagus": true,
  "Aspartame": true,
  "Aspartic acid": true,
  "Astragalus": false,
  "Avocado oil": true,
  "Avocadoes": true,
  "Bacon": true,
  "Baker's yeast": false,
  "Baking powder": false,
  "Baking soda": true,
  "Balsamic vinegar": false,
  "Bananas": true,
  "Bark tea": false,
  "Barley": false,
  "Basil": true,
  "Bay Leaf": true,
  "Bean flour": false,
  "Bean sprouts": false,
  "Bee Pollen": false,
  "Beef": true,
  "Beer": false,
  "Beets": true,
  "Berries": true,
  "Bhindi": false,
  "Bitter Gourd": false,
  "Black beans": true,
  "Black eye beans": false,
  "Black radish": true,
  "Blue cheese": true,
  "Bok Choy": true,
  "Bologna": false,
  "Bouillon cubes": false,
  "Bourbon": true,
  "Brandy": false,
  "Brazil nuts": true,
  "Brick cheese": true,
  "Brie cheese": true,
  "Broccoli": true,
  "Brussell sprouts": true,
  "Buckwheat": false,
  "Bulgur": false,
  "Burdock root": false,
  "Butter": true,
  "Butter beans": false,
  "Buttermilk": false,
  "Butternut squash": true,
  "Cabbage": true,
  "Camembert cheese": true,
  "Canellini beans": false,
  "Canned fish": true,
  "Canned fruits": false,
  "Canned vegetables": false,
  "Canola oil": true,
  "Cantaloupe": true,
  "Capers": true,
  "Carob": false,
  "Carrageenan": false,
  "Carrots": true,
  "Cashews": true,
  "Cauliflower": true,
  "Celeriac /celery root": true,
  "Celery": true,
  "Cellulose (in supplements)": true,
  "Cellulose Gum": false,
  "Cereals": false,
  "Chard": true,
  "Cheddar cheese": true,
  "Cheese": true,
  "Cherimoya": true,
  "Cherries": true,
  "Chestnut flour": false,
  "Chestnuts": true,
  "Chevre": false,
  "Chewing gum": false,
  "Chick peas": false,
  "Chickory root": false,
  "Chlorella": false,
  "Chocolate": false,
  "Cilantro": true,
  "Cinnamon": true,
  "Citric Acid": true,
  "Club soda": true,
  "Cocoa powder": false,
  "Coconut": true,
  "Coconut milk": true,
  "Coconut oil": true,
  "Coffee": true,
  "Coffee (instant)": false,
  "Colby cheese": true,
  "Collard greens": true,
  "Cordials": false,
  "Corn": false,
  "Corn oil": true,
  "Corn syrup": false,
  "Cornstarch": false,
  "Cottage cheese": false,
  "Courgette": true,
  "Cranberry juice": true,
  "Cream": false,
  "Cream cheese": false,
  "Cream of Tartar": false,
  "Croscomellose sodium": false,
  "Cucumbers": true,
  "Custard apple": true,
  "Cyclamate": true,
  "Date sugar": false,
  "Dates": true,
  "Decaffeinated Products": false,
  "Dextrose (contained in commercial products)": false,
  "Dried milk solids": false,
  "Drumsticks": false,
  "Dry Curd Cottage Cheese (DCCC)": true,
  "Durum Flour": false,
  "Echinacea": true,
  "Edam cheese": true,
  "Eggplant": true,
  "Eggs": true,
  "EMPower": false,
  "Ethanol": true,
  "Evaporated cane juice": false,
  "Ezekiel Bread": false,
  "Faba beans": false,
  "Fenugreek": false,
  "Feta Cheese": false,
  "Figs": true,
  "Filberts (hazelnuts)": true,
  "Fish": true,
  "Flax seed": false,
  "Flax seed oil": true,
  "Flour": false,
  "FOS": false,
  "Fowl": true,
  "Frozen Orange Juice (concentrated)": false,
  "Fructose (granulated)": false,
  "Fruits (canned)": true,
  "Garbanzo beans": false,
  "Garfava flour": false,
  "Garlic": true,
  "Gelatin (unflavored)": true,
  "Ghee": true,
  "Gin": true,
  "Ginger": true,
  "Gjetost cheese": false,
  "Glucose candy": false,
  "Glycerin": true,
  "Glycerol": true,
  "Goatein": false,
  "Gorgonzola cheese": true,
  "Gouda cheese": true,
  "Granulated glucose": false,
  "Grape juice": true,
  "Grapefruit": true,
  "Grapefruit juice": false,
  "Grapes": true,
  "Grapeseed oil": true,
  "Green tea": true,
  "Gruyere cheese": true,
  "Guar Gum": false,
  "Gums": false,
  "Ham": true,
  "Haricot beans": true,
  "Havarti cheese": true,
  "Hazelnuts (filberts)": true,
  "Hemp seed, Hemp protein powder": false,
  "HN-Zyme": true,
  "Homemade yogurt": true,
  "Honey": true,
  "Horseradish sauce": true,
  "Hot dogs": false,
  "Hydrolyzed Protein": false,
  "Ice cream": false,
  "Inositol": false,
  "Inulin": false,
  "Iron supplements": false,
  "Isoglucose": false,
  "Jaggery (gur)": false,
  "Jalapenos": true,
  "Jicama": false,
  "Juice from concentrate": false,
  "Kale": true,
  "Kefir": false,
  "Ketchup": false,
  "Kidney beans": true,
  "Kimchi": true,
  "Kiwi fruit": true,
  "Kohlrabi": false,
  "Kudzu (or kuzu)": false,
  "Kumquats": true,
  "KyoGreen powder": false,
  "L-Theanine": true,
  "Lactaid Milk": false,
  "Lactose Hydrolyzed Milk": false,
  "Lamb": true,
  "Lecithin": true,
  "Leek": true,
  "Lemons": true,
  "Lentils": true,
  "Lettuce": true,
  "leucine": true,
  "Licorice": false,
  "Lignin": false,
  "Lima beans": true,
  "Limburger cheese": true,
  "Limes": true,
  "Liqueurs": false,
  "Liquid Clorychlorophyll": false,
  "Macadamia nuts": true,
  "Macadamia oil": true,
  "Magnesium citrate": true,
  "Magnesium Stearate": true,
  "Maltitol": false,
  "Maltodextrin": false,
  "Manchego Cheese": true,
  "Mangoes": true,
  "Mannitol": false,
  "Maple syrup": false,
  "Margarine": false,
  "Marshmallow": false,
  "Mastic gum": false,
  "Mead": false,
  "Meats": true,
  "Meats (canned)": false,
  "Meats (processed)": false,
  "Melatonin": false,
  "Melon": true,
  "Milk": false,
  "Millet": false,
  "Miso": false,
  "Molasses": false,
  "Molo-cure": false,
  "Monterey Jack cheese": true,
  "Mozzarella cheese": false,
  "MSG": false,
  "Mucilaginous Herbs": false,
  "Mucilaginous Polysaccharides": false,
  "Muenster cheese": true,
  "Mungbeans": false,
  "Mushrooms": true,
  "Mustard (plain)": true,
  "Natural cheeses": true,
  "Natural Flavors": false,
  "Navy beans": true,
  "Nectarines": true,
  "Nettles": false,
  "Neufchatel cheese": false,
  "Noni Juice": false,
  "Nutmeg": true,
  "Oats": false,
  "Okra": false,
  "Olive oil": true,
  "Olives": true,
  "Onions": true,
  "Orange juice": true,
  "Oranges": true,
  "Oregano": true,
  "Papayas": true,
  "Pappadum": false,
  "Paprika": true,
  "Parmesan cheese": true,
  "Parsley": true,
  "Parsnips": false,
  "Passion Fruit": true,
  "Pasta": false,
  "Pau 'Arco": false,
  "Pea flour": false,
  "Peaches": true,
  "Peanut butter": true,
  "Peanut Oil": true,
  "Peanuts": true,
  "Pears": true,
  "Peas": true,
  "Pecans": true,
  "Pectin": false,
  "Peppermint tea": true,
  "Peppers": true,
  "Peptizyde": true,
  "Persimmons": true,
  "Phosphatidylcholine": true,
  "Pickles (dill)": true,
  "Pine nuts": true,
  "Pineapple": true,
  "Pineapple juice": false,
  "Pinto beans": false,
  "Pistachio nuts": true,
  "Plantains": false,
  "Plums": true,
  "Polysorbate 80": false,
  "Pomegranate concentrate": false,
  "Pork": true,
  "Pork Rinds": true,
  "Port du Salut cheese": true,
  "Port wine": false,
  "Postum": false,
  "Potassium Sorbate": true,
  "Potatoes": false,
  "Poultry": true,
  "Primal Defense": false,
  "Primost cheese": false,
  "Processed cheeses": false,
  "Protein powder": false,
  "Provolone cheese": true,
  "Prunes": true,
  "Psyllium husks": false,
  "Pumpkin": true,
  "Pumpkin (canned)": false,
  "Quinoa": false,
  "Quorn": false,
  "Raisins": true,
  "Rhubarb": true,
  "Rice": false,
  "Rice Bran": false,
  "Rice Flour": false,
  "Ricotta cheese": false,
  "Romano cheese": true,
  "Roquefort cheese": true,
  "Rosemary": true,
  "Rutabaga": true,
  "Rye": false,
  "Saccharine": true,
  "Safflower oil": true,
  "Sage": true,
  "Sago starch": false,
  "Sake": false,
  "Salt": true,
  "Sashimi": true,
  "saukerkraut": true,
  "Seaweed": false,
  "Seed Butters": false,
  "Seed Flour": false,
  "Seeds": true,
  "Sesame oil": true,
  "Sesame seeds": false,
  "Sharifa": true,
  "Shellfish": true,
  "Sherry": false,
  "Silica": true,
  "Silicon Dioxide": true,
  "Slippery elm": false,
  "Smoked meats": false,
  "Sodium Benzoate": true,
  "Sodium starch glycinate": false,
  "Sorbitol": false,
  "Sour cream": false,
  "Soy": false,
  "Soy Lecithin": true,
  "Soy Sauce": false,
  "Soybean milk": false,
  "Soybean oil": false,
  "Soybeans": false,
  "Spearmint Tea": true,
  "Spelt": false,
  "Spices": true,
  "Spinach": true,
  "Spirulina": false,
  "Splenda": false,
  "Split peas": true,
  "Sprouted Grain Bread": false,
  "Squash": true,
  "Stevia": false,
  "Stilton cheese": true,
  "String beans": true,
  "Sucralose": false,
  "Sulphates": true,
  "Sunflower oil": true,
  "Swede": true,
  "Sweet Potatoes": false,
  "Swiss cheese": true,
  "Tabasco sauce": false,
  "Tagatose": false,
  "Tamari": false,
  "Tamarind": false,
  "Tangerines": true,
  "Tapioca": false,
  "Tapioca Flour": false,
  "Taro": false,
  "Tarragon": true,
  "Tea": true,
  "Thyme": true,
  "Tofu": false,
  "Tofutti cheese": false,
  "tomato": true,
  "Tomato juice (canned)": true,
  "Tomato paste (canned)": false,
  "Tomato purée (canned)": false,
  "Tomato sauce (canned)": false,
  "Triticale": false,
  "Turbinado": false,
  "Turnips": false,
  "V8 Juice": false,
  "Vanillin": true,
  "Vegetable stearate": true,
  "Vegetables (canned)": false,
  "Vinegar": true,
  "Vodka": true,
  "Walnut oil": true,
  "Walnuts": true,
  "Wasabi": true,
  "Water chestnuts": false,
  "Watercress": true,
  "Watermelon": true,
  "Wheat": false,
  "Wheat germ": false,
  "Whisky": true,
  "Wine": true,
  "Xanthum Gum": false,
  "Xylitol": false,
  "Yams": false,
  "Yoghurt (commercial)": false,
  "Yoghurt (homemade)": true,
  "Yucca Root": false,
  "Zucchini": true
};
